import { Poppins } from "next/font/google";
import StoreProvider from "@/src/store/Provider";

import "./globals.css";
import { ToastContainer } from "react-toastify";
import NextTopLoader from "nextjs-toploader";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  height: "device-height",
  initialScale: 1,
  maximumScale: 2,
  minimumScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className + " bg-body-color"}>
        <StoreProvider>
          <NextTopLoader
            color="#5E35CC"
            height={3}
            speed={500}
            showSpinner={false}
          />
          <ToastContainer style={{ marginTop: "100px" }} autoClose={3000} />
        </StoreProvider>
        {children}
      </body>
    </html>
  );
}
